export const products = [
  {
    id: "1",
    title: "BXN 2008 - Hoodie",
    slug: "",
    price: 1620,
    discount: 10,
    quantity: 50,
    colors: ["Black", "Blue"],
    sizes: ["M", "L", "XL"],
    images: [
      "https://barraserb.com/cdn/shop/files/brsrb1.png",
      "https://barraserb.com/cdn/shop/files/brsrb2.png",
      "https://barraserb.com/cdn/shop/files/brsrb3.png",
      "https://barraserb.com/cdn/shop/files/brsrb4.png",
      "https://barraserb.com/cdn/shop/files/Photopea_Image_1.png",
    ],
    description:
      "A transmission interrupted. Inspired by digital static and fragmented visuals the Fractured Signal Hoodie brings together NMR’s signature graphic deconstruction with Barraserb’s raw aesthetic.",
  },
  {
    id: "2",
    title: "BX'N' 1,370°C - Black long sleeve",
    slug: "",
    price: 1280,
    discount: 15,
    quantity: 30,
    colors: ["Brown", "Black"],
    sizes: ["M", "L", "XL"],
    images: [
      "https://barraserb.com/cdn/shop/files/brsrb22.png",
      "https://barraserb.com/cdn/shop/files/Image_5_from_Photopea.png",
      "https://barraserb.com/cdn/shop/files/Photopea_Image_7.png",
      "https://barraserb.com/cdn/shop/files/brsrb23.png",
      "https://barraserb.com/cdn/shop/files/brsrb25.png",
      "https://barraserb.com/cdn/shop/files/brsrb24.png",
      "https://barraserb.com/cdn/shop/files/Photopea_Image_6.png",
      "https://barraserb.com/cdn/shop/files/Photopea_Image_5.png",
    ],
    description:
      "A two-tone spray effect meets fragmented graphics in this long sleeve from the Barraserb x NMR collaboration.Built for high-impact visuals,",
  },
  {
    id: "3",
    title: "BX'N MATHACRYLATE - long sleeve",
    slug: "",
    price: 1280,
    discount: 20,
    quantity: 20,
    colors: ["Green", "Black"],
    sizes: ["M", "L", "XL"],
    images: [
      "https://barraserb.com/cdn/shop/files/brsrb10.png",
      "https://barraserb.com/cdn/shop/files/brsrb9.png",
      "https://barraserb.com/cdn/shop/files/brsrb11.png",
      "https://barraserb.com/cdn/shop/files/brsrb12.png",
      "https://barraserb.com/cdn/shop/files/Photopea_Image_4.png",
    ],
    description:
      "Erosion, distortion, and digital decay—this Barraserb x NMR long sleeve fuses layered textures with deconstructed graphics, channeling the essence of visual breakdown.",
  },
  {
    id: "4",
    title: "BXN IDTRB - T-shirt",
    slug: "",
    price: 800,
    discount: 20,
    quantity: 20,
    colors: ["Pink", "Brown"],
    sizes: ["S", "M", "L", "XL"],
    images: [
      "https://barraserb.com/cdn/shop/files/brsrb33.png",
      "https://barraserb.com/cdn/shop/files/brsrb34.png",
      "https://barraserb.com/cdn/shop/files/brsrb35.png",
      "https://barraserb.com/cdn/shop/files/brsrb36.png",
    ],
    description:
      "A raw expression of movement and distortion. The IDTRB Tee captures the essence of controlled chaos, blending spray-treated graphics and distressed textures into a wearable statement.",
  },
];
